<?php

namespace App\Models;

//use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Scopes\OfferScope;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static get()
 */
class Offer extends Model
{
  //  use HasFactory;

    protected $table="offers";
    protected $fillable=['name_ar','name_en','price', 'details_ar','details_en','photo'];
    protected $hidden=['created_at','updated_at'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new OfferScope);
    }

    public function scopeInactive($q){
        return $q->where('status',0);
    }

    public function scopeInvalid($q){
        return $q->where('status',0)->whereNull('details_ar');
    }

}
